/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Pattern;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;
import model.NhanVien;
import service.NhanVienService;
import view.DangNhap;

public class QuenMatKhauJDialog extends javax.swing.JDialog {

    private final NhanVienService dao = new NhanVienService();
    private String OTP;
    private String to;
    private long otpStartTime;

    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtMaxacnhan.setEnabled(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        txtPassOld.setVisible(false);
        txtPassNew1.setVisible(false);
        txtPassNew2.setVisible(false);
        btnDoiMK.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLayMa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaxacnhan = new javax.swing.JTextField();
        btnDoiMK = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassOld = new javax.swing.JPasswordField();
        txtPassNew1 = new javax.swing.JPasswordField();
        txtPassNew2 = new javax.swing.JPasswordField();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quên Mật Khẩu");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnLayMa.setBackground(new java.awt.Color(255, 255, 255));
        btnLayMa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLayMa.setText("Lấy Mã");
        btnLayMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayMaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Mã OTP:");

        txtMaxacnhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDoiMK.setBackground(new java.awt.Color(255, 255, 0));
        btnDoiMK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(255, 0, 51));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Mật khẩu cũ:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Mật khẩu mới:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Xác nhận:");

        btnXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLayMa))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassOld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassNew1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassNew2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoiMK)
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayMa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassOld, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassNew2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLayMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayMaActionPerformed
        if (checkmail()) {
            return;
        }

        // Nếu email hợp lệ, thực hiện gửi mã OTP
        try {
            btnLayMa.setEnabled(true);
            btnDoiMK.setEnabled(true);
            // Cấu hình thông tin email
            Properties properties = new Properties();
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", 587);

            // Thông tin đăng nhập email
            String username = "quanlybandienthoaimobileshop4@gmail.com"; // Thay bằng địa chỉ email của bạn
            String password = "iubs fhfs tdvj ikxo"; // Thay bằng mật khẩu email của bạn

            // Tạo phiên gửi email
            Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            });

            // Gửi mã OTP
            String from = username;
            to = txtEmail.getText();
            OTP = generateOTP();
            String title = "Quên mật khẩu";

            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(title);
            msg.setText("Mã OTP: " + OTP + " Đây là mã OTP của bạn, sẽ hết hạn trong vòng 3 phút. Vui lòng không để lộ thông tin này!");

            // Sử dụng Transport.send() để gửi
            Transport.send(msg);

            // Lưu thời điểm khi gửi mã OTP để kiểm tra hết hạn
            otpStartTime = System.currentTimeMillis();

            HienThiND.ND(this, "Đã gửi mã OTP! Hãy kiểm tra email của bạn.");
            txtMaxacnhan.setEnabled(true);
        } catch (AuthenticationFailedException e) {
            e.printStackTrace();
            HienThiND.ND(this, "Lỗi xác thực. Vui lòng kiểm tra lại thông tin đăng nhập.");
        } catch (MessagingException e) {
            e.printStackTrace();
            HienThiND.ND(this, "Đã xảy ra lỗi khi gửi mã OTP. Vui lòng thử lại sau.");
        }
    }//GEN-LAST:event_btnLayMaActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát?", "HUỶ", JOptionPane.YES_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();
            new DangNhap(new javax.swing.JFrame(), true).setVisible(true);
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if (checkOTP()) {
            return;
        } else {
            if (isOTPExpired()) {
                HienThiND.ND(this, "Mã OTP đã hết hạn. Vui lòng gửi lại mã mới.");
                btnLayMa.setEnabled(true); // Cho phép gửi lại mã
                btnDoiMK.setEnabled(false); // Disable nút "Xác nhận" nếu mã hết hạn
            } else {
                confirmCode();
                //dispose();
            }
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLayMa;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaxacnhan;
    private javax.swing.JPasswordField txtPassNew1;
    private javax.swing.JPasswordField txtPassNew2;
    private javax.swing.JPasswordField txtPassOld;
    // End of variables declaration//GEN-END:variables

    private boolean checkmail() {
        String Email = "^[\\w-_.+]*[\\w-_.]@(gmail\\.com|fpt\\.edu\\.vn)$";

        String mail = txtEmail.getText().trim();
        if (txtEmail.getText().isEmpty()) {
            HienThiND.ND(this, "Chưa nhập email");
            return true;
        } else if (!mail.matches(Email)) {
            HienThiND.ND(this, "Định dạng email không hợp lệ!");
            return true;
        } else {
            // Kiểm tra xem có tài khoản nào đăng ký bằng email này hay không
            NhanVienService daonv = new NhanVienService();
            if (daonv.selectByEmail(txtEmail.getText()) == null) {
                HienThiND.ND(this, "Không có tài khoản nào đăng ký bằng email này!");
                return true;
            }
        }
        return false;
    }

    private String generateOTP() {
        Random rd = new Random();
        int numbercode = rd.nextInt(9000) + 1000;
        return String.valueOf(numbercode);
    }

    private boolean checkOTP() {
        if (txtMaxacnhan.getText().isEmpty()) {
            HienThiND.ND(this, "Mã xác nhận trống");
            return true;
        }

        // Kiểm tra xem mã OTP có còn hiệu lực không
        if (isOTPExpired()) {
            HienThiND.ND(this, "Mã OTP đã hết hạn. Vui lòng gửi lại mã mới.");
            return true;
        }

        Pattern regex = Pattern.compile("[a-zA-Z]");
        if (regex.matcher(txtMaxacnhan.getText()).find()) {
            HienThiND.ND(rootPane, "Mã OTP sai định dạng!");
            return true;
        }

        return false;
    }

    private void confirmCode() {
        if (txtMaxacnhan.getText().equals(OTP)) {
            HienThiND.ND(this, "Mã OTP chính xác!\nHãy đổi lại mật khẩu.");
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            txtPassOld.setVisible(true);
            txtPassNew1.setVisible(true);
            txtPassNew2.setVisible(true);
            btnDoiMK.setVisible(true);
        } else {
            HienThiND.ND(this, "Mã OTP không chính xác!");
            txtMaxacnhan.requestFocus();
        }
    }

    private boolean isOTPExpired() {
        // Lấy thời điểm hiện tại
        long currentTime = System.currentTimeMillis();
        // Kiểm tra xem đã qua 3 phút từ thời điểm bắt đầu gửi mã hay chưa
        return currentTime > (otpStartTime + 3 * 60 * 1000);
    }
//------------------------------------------------------------------------------------------------------------------------------

    private void doiMatKhau() {
        String email = txtEmail.getText();
        String matKhauCu = new String(txtPassOld.getPassword());
        String matKhauMoi = new String(txtPassNew1.getPassword());
        String xacNhanMatKhauMoi = new String(txtPassNew2.getPassword());

        if (email.isEmpty() && matKhauCu.isEmpty() && matKhauMoi.isEmpty() && xacNhanMatKhauMoi.isEmpty()) {
            HienThiND.ND(this, "Vui lòng nhập thông tin.");
            return;
        }
        if (email.isEmpty()) {
            HienThiND.ND(this, "Vui lòng nhập mail đăng nhập");
            return;
        }
        if (matKhauCu.isEmpty()) {
            HienThiND.ND(this, "Vui lòng nhập mật khẩu cũ");
            return;
        }
        if (matKhauMoi.isEmpty()) {
            HienThiND.ND(this, "Vui lòng nhập mật khẩu mới");
            return;
        }

        if (matKhauMoi.isEmpty() || xacNhanMatKhauMoi.isEmpty()) {
            HienThiND.ND(this, "Vui lòng nhập lại mật khẩu mới");
            return;
        }

        if (!matKhauMoi.equals(xacNhanMatKhauMoi)) {
            HienThiND.ND(this, "Mật khẩu xác nhận không đúng!");
            return;
        }

        NhanVien nv = dao.selectByEmail(email);
        if (nv == null) {
            HienThiND.ND(this, "Tên đăng nhập không tồn tại!");
            return;
        }

        if (!nv.getMatKhau().equals(matKhauCu)) {
            HienThiND.ND(this, "Sai mật khẩu cũ!");
            clearForm();
            return;
        }

        nv.setMatKhau(matKhauMoi);
        dao.updateMKMail(nv);

        HienThiND.ND(this, "Đổi mật khẩu thành công!\nVui lòng đăng nhập lại");
        dispose();
        TrangChu trangChu = new TrangChu();
        trangChu.setVisible(true);
        //dispose();
    }

    public static class HienThiND {

        public static void ND(Component parent, String mess) {
            JOptionPane.showMessageDialog(parent, mess, "Hệ thống quản lý bán điện thoại", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void clearForm() {
        txtPassOld.setText("");
        txtPassNew1.setText("");
        txtPassNew2.setText("");
    }
}
